askcompany/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('shop/', include('shop.urls')),
]

# 개발환경에서의 media 파일 서빙
# DEBUG 옵션이 참일때만 동작, 참이 아니면 빈리스트 리턴
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

blog/urls.py
from django.urls import path

app_name = 'blog'

urlpatterns = [

]

shop/urls.py
from django.urls import path, register_converter
from .converters import FourDigitYearConverter
from . import views

register_converter(FourDigitYearConverter, 'yyyy')

# url reverse에서 namespace
app_name = 'shop'

urlpatterns = [
    path('', views.item_list, name='item_list'),
    path('<int:pk>/', views.item_detail, name='item_detail'),
    path('new/', views.item_new, name='item_new'),
    path('<int:pk>/edit/', views.item_edit, name='item_edit'),
]

blog/models.py
from django.conf import settings
from django.db import models
from askcompany.utils import uuid_upload_to

class Post(models.Model):
    author_name = models.CharField(max_length=20)
    title = models.CharField(max_length=100)
    content = models.TextField()
    photo = models.ImageField(upload_to=uuid_upload_to)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    # on_delete옵션은 foreignkey로 post와 연결되어 있는데
    # 만약 post가 없어지면 이 comment model도 삭제할 것인지 여부를 결정하는 것
    # cascade는 같이 삭제하겠다는 옵션
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    message = models.TextField()

common/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse

from askcompany.utils import uuid_upload_to


class Item(models.Model):
  name = models.CharField(max_length=100)
  desc = models.TextField(blank=True)
  photo = models.ImageField(blank=True, upload_to=uuid_upload_to)
  price = models.PositiveIntegerField()
  is_publish = models.BooleanField(default=False)
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

  def __str__(self):
    # return '<{}> {}'.format(self.pk, self.name)
    return f'<{self.pk}> {self.name}'

  def get_absolute_url(self):
    # args: 튜플, kwargs: 딕셔너리
    # return reverse('shop:item_detail', args=[self.pk])
    # 얘랑 같은 의미
    # shop은 namespace, item_detail은 url에서 name지정해 준 것
    return reverse('shop:item_detail', kwargs={'pk': self.pk})
    # 여기서 'pk'는 urls.py에 있는 <int:pk>의 pk와 맞춰주는 것!

class Post(models.Model):
  author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


    

shop/forms.py
from django import forms
from .models import Item

# class ItemForm(forms.Form):
#     name = forms.CharField()
#     desc = forms.CharField(widget=forms.Textarea)

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = '__all__'  # 이렇게 하면 위처럼 필드 각각 정의 안해도 됨 (admin에서 같은 방식 사용, 물론 custom도 가능)

blog/views.py
from django.urls import path, register_converter
from .converters import FourDigitYearConverter
from . import views

register_converter(FourDigitYearConverter, 'yyyy')

app_name = 'blog'

urlpatterns = [
    path('archives/<yyyy:year>/', views.archives_year),

]

common/views.py
from django.shortcuts import render

# Create your views here.

shop/views.py
import logging
import re

from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, request
from django.views.generic import CreateView, UpdateView
from .models import Item
from .forms import ItemForm

logger = logging.getLogger(__name__)  # __name__ => "shop.views"
                                      #즉, settings.py에서 loggers에 추가해줘야함

def item_list(request):
  qs = Item.objects.all()

  # q가 없으면 빈문자열 받아오겠다
  q = request.GET.get('q', '')
  if q:
    #icontains : ignore case 대소문자 구분x
    qs = qs.filter(name__icontains=q)

  logger.debug('query : {}'.format(q))
  
  return render(request, 'shop/item_list.html', {
    'item_list' : qs,
    #검색어 보존
    'q' : q
  })

#인자는 url, 즉, get요청으로부터 받는 듯..?
def item_detail(request, pk):
  item = get_object_or_404(Item, pk=pk)
  return render(request, 'shop/item_detail.html', {
    'item' : item,
  })


# # 장고 form을 안쓰면 이렇게 힘들다
# def item_new(request, item=None):
#   if request.method == 'POST':
#     form = ItemForm(request.POST, request.FILES, instance=item)   # 순서 바꾸면 안됨
#     if form.is_valid():
#       item = form.save()   # ModelForm에서 제공해주는 기능
#       return redirect(item)
#
#   else: #GET 요청일 때
#     form = ItemForm(instance=item)  #instance도 ModelForm에서 지원, edit 구현 위해 넘겨준다
#
#   return render(request, 'shop/item_form.html', {
#     'form' : form,
#   })
#
#
# def item_edit(request, pk):
#   item = get_object_or_404(Item, pk=pk)
#   return item_new(request, item)


# 얘네 내부 코드가 위에 있는 것들
# 나중 코스에서 다룬다
item_new = CreateView.as_view(model=Item, form_class=ItemForm)
item_edit = UpdateView.as_view(model=Item, form_class=ItemForm)

askcompany/templates/layout.html
{% load static fresh_static%}
<!DOCTYPE html>
<html lang="en">
    <head>
      <meta charset="UTF-8">
{#        scale을 x1.0 고정으로, 유저이 배율 조정을 막겠다는 뜻#}
      <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
      <title>{% block title %}AskCompany{% endblock %}</title>
      <style>
          body{
              background-color: lightyellow;
          }
      </style>
        {% block extra_head %}
            <link rel="stylesheet" href="{% fresh_static "main.css" %}" />
        {% endblock %}
    </head>
    <body>
        <h1>Ask Company</h1>

        {% block content %}
{#            block 이름이 content#}
        {% endblock %}

        <hr/>
        &copy: 2018. Ask Company.
        {% block extra_body %}
            <script src="{% static "main.js" %}"></script>
        {% endblock %}
    </body>
</html>

blog/templates/blog/layout.html
{% extends "layout.html" %}
{% load static fresh_static %}

{% block title %}Blog by Ask Company{% endblock %}

{% block extra_head %}
    {{ block.super }}
    <link rel="stylesheet" href="{% fresh_static "blog/blog.css" %}"/>
{% endblock %}

{% block extra_body %}
    {{ block.super }}
{% endblock %}

shop/templates/shop/item_detail.html
{% extends "shop/layout.html" %}
{% load humanize %}

{% block content %}
        <h2>{{ item.name }}</h2>
{#        없으면 오류뜨니까 항상 if처리!#}
        {% if item.photo %}
    {#        실제 db에 저장된 문자열이 찍힘#}
{#            {{ item.photo }}#}
    {#        내부적으로 url 만들어줌#}
{#            {{ item.photo.url }}#}
    {#        실제 media 루트 보여줌#}
{#            {{ item.photo.path }}#}

{#            다운로드하게 하려면 태그 바꿔주기, 이건 그냥 사진 보여주는 것#}
            <img src="{{ item.photo.url }}" style="max-width: 100%" />
            <br/>
        {% endif %}

        가격: {{ item.price|intcomma }} 원

        {% if item.desc %}
            <p>
                {{ item.desc }}
            </p>
        {% endif %}

        <hr/>
        <a href="{% url "shop:item_list" %}">목록</a>
        <a href="{% url "shop:item_edit" item.pk %}">수정</a>
{% endblock %}

shop/templates/shop/item_form.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8" />
        <title></title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" />
    </head>
    <body>
        <div class="container">
            <div class="col-sm-12">
                <h2>New Item</h2>


{#                action부분이 빔: 이 form이 보여지는 같은 주소로 요청을 보내겠다는 뜻#}
{#                action은 form을 보낼 주소임#}
{#                method는 오타없이 잘 입력하기#}
{#                파일 보낼 때는 항상 enctype!#}
                <form action="" method="post" enctype="multipart/form-data" autocomplete="off">
                    {% csrf_token %}

                    <table class="table table-bordered">
                        {{ form.as_table }}
                    </table>
{#                    폼에 값 잘못 입력하면 빨갛게 표시되고 알림 뜨는거는 장고에서 제공하는게 아니라 브라우저 기능임#}

                    <input type="submit" value="저장하기" class="btn btn-primary" />
                </form>
            </div>
        </div>
    </body>
</html>

shop/templates/shop/item_list.html
{% extends "shop/layout.html" %}

{% block content %}
        <form action="" method="GET">
            <input type="text" name="q" value="{{q}}"/>
            <input type="submit" value="search" />
        </form>
        <ul>
            {%  for item in item_list %}
                <li>
{#                    드디어 url reverse 사용!#}
                    <a href="{{ item.get_absolute_url }}">
                        {{ item.name }}
                    </a>
                    {{ item.price }}
                    {{ item.desc }}
                </li>
            {% endfor %}
        </ul>
        <hr/>
        <a href="{% url "shop:item_new" %}">New Item</a>
{% endblock %}

shop/templates/shop/item_list.jinja
<!DOCTYPE html>
<html lang="en">
    <head>
      <meta charset="UTF-8">
      <title>Title</title>
    </head>
    <body>
        <h1>Ask Company</h1>

{#        함수 호출을 하지 않은 형태로 출력, 기본 DTL 문법#}
{#        {{ item_list.first }}#}
{#        함수호출#}
{#        {{ item_list.first() }}#}

{#        context processor 중 auth 덕분에 유저가 찍힘#}
        {{ user }}

        <form action="" method="GET">
            <input type="text" name="q" value="{{q}}"/>
            <input type="submit" value="search" />
        </form>
        <ul>
            {%  for item in item_list %}
                <li>
                    {{ item.name }}
                    {{ item.price }}
                    {{ item.desc }}
                </li>
            {% endfor %}
        </ul>
    </body>
</html>

shop/templates/shop/layout.html
{% extends "layout.html" %}
{% load static fresh_static%}
{#파일 템플릿 로더가 참조하는 경로가 askcompany/templates니까 이대로 써줌#}

{% block title %}Shop by Ask Company{% endblock %}

{% block extra_head %}
    {{ block.super }}
    <link rel="stylesheet" href="{% fresh_static "shop/shop.css" %}"/>
{% endblock %}

{% block extra_body %}
    {{ block.super }}
{% endblock %}